spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mig1511/green-alphabet-config-server.git
          username:
          password:
          clone-on-start: true


server:
  port: 8888